# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Initialize.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Wizard(object):
    def setupUi(self, Wizard):
        Wizard.setObjectName("Wizard")
        Wizard.setEnabled(True)
        Wizard.resize(559, 676)
        Wizard.setMinimumSize(QtCore.QSize(559, 676))
        Wizard.setMaximumSize(QtCore.QSize(559, 676))
        Wizard.setTabletTracking(False)
        Wizard.setSizeGripEnabled(True)
        self.wizardPage1 = QtWidgets.QWizardPage()
        self.wizardPage1.setAutoFillBackground(True)
        self.wizardPage1.setObjectName("wizardPage1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.wizardPage1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.wizardPage1)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_2.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(12)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(12)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        Wizard.addPage(self.wizardPage1)
        self.wizardPage2 = QtWidgets.QWizardPage()
        self.wizardPage2.setTitle("")
        self.wizardPage2.setSubTitle("")
        self.wizardPage2.setObjectName("wizardPage2")
        self.label_2 = QtWidgets.QLabel(self.wizardPage2)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 121, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(self.wizardPage2)
        self.textEdit.setGeometry(QtCore.QRect(130, 40, 381, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setObjectName("textEdit")
        self.label_3 = QtWidgets.QLabel(self.wizardPage2)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 211, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.listWidget = QtWidgets.QListWidget(self.wizardPage2)
        self.listWidget.setGeometry(QtCore.QRect(10, 130, 481, 201))
        self.listWidget.setObjectName("listWidget")
        self.progressBar = QtWidgets.QProgressBar(self.wizardPage2)
        self.progressBar.setGeometry(QtCore.QRect(30, 390, 481, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        Wizard.addPage(self.wizardPage2)
        self.wizardPage3 = QtWidgets.QWizardPage()
        self.wizardPage3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.wizardPage3.setToolTipDuration(-1)
        self.wizardPage3.setObjectName("wizardPage3")
        self.label_4 = QtWidgets.QLabel(self.wizardPage3)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 281, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        Wizard.addPage(self.wizardPage3)

        self.retranslateUi(Wizard)
        Wizard.accepted.connect(Wizard.next)
        self.listWidget.pressed['QModelIndex'].connect(Wizard.selectPhyDrive_button)
        self.radioButton.clicked.connect(Wizard.setNewCase_button)
        QtCore.QMetaObject.connectSlotsByName(Wizard)

    def retranslateUi(self, Wizard):
        _translate = QtCore.QCoreApplication.translate
        Wizard.setWindowTitle(_translate("Wizard", "Initialize"))
        self.radioButton_2.setText(_translate("Wizard", "Load Recent case"))
        self.label.setText(_translate("Wizard", "Welcome"))
        self.radioButton.setText(_translate("Wizard", "New case"))
        self.label_2.setText(_translate("Wizard", "Case name : "))
        self.textEdit.setHtml(_translate("Wizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'맑은 고딕\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("Wizard", "Select Target Disk"))
        self.label_4.setText(_translate("Wizard", "Creating case has finished."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Wizard = QtWidgets.QWizard()
    ui = Ui_Wizard()
    ui.setupUi(Wizard)
    Wizard.show()
    sys.exit(app.exec_())

