# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1235, 876)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.previous_button = QtWidgets.QPushButton(self.centralwidget)
        self.previous_button.setMaximumSize(QtCore.QSize(64, 64))
        self.previous_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/UI_resource/documents-document-previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/UI_resource/documents-document-previous-disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.previous_button.setIcon(icon)
        self.previous_button.setIconSize(QtCore.QSize(64, 64))
        self.previous_button.setCheckable(False)
        self.previous_button.setFlat(True)
        self.previous_button.setObjectName("previous_button")
        self.horizontalLayout_3.addWidget(self.previous_button)
        self.next_button = QtWidgets.QPushButton(self.centralwidget)
        self.next_button.setMaximumSize(QtCore.QSize(64, 64))
        self.next_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/UI_resource/documents-document-next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/UI_resource/documents-document-next-disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.next_button.setIcon(icon1)
        self.next_button.setIconSize(QtCore.QSize(64, 64))
        self.next_button.setFlat(True)
        self.next_button.setObjectName("next_button")
        self.horizontalLayout_3.addWidget(self.next_button)
        self.upper_button = QtWidgets.QPushButton(self.centralwidget)
        self.upper_button.setMaximumSize(QtCore.QSize(64, 64))
        self.upper_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/UI_resource/documents-document-up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/UI_resource/documents-document-up-disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.upper_button.setIcon(icon2)
        self.upper_button.setIconSize(QtCore.QSize(64, 64))
        self.upper_button.setFlat(True)
        self.upper_button.setObjectName("upper_button")
        self.horizontalLayout_3.addWidget(self.upper_button)
        self.whitelisting_button = QtWidgets.QPushButton(self.centralwidget)
        self.whitelisting_button.setMaximumSize(QtCore.QSize(200, 48))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.whitelisting_button.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/UI_resource/audio-and-sound-slider-controls.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.whitelisting_button.setIcon(icon3)
        self.whitelisting_button.setIconSize(QtCore.QSize(48, 48))
        self.whitelisting_button.setCheckable(False)
        self.whitelisting_button.setAutoDefault(False)
        self.whitelisting_button.setDefault(True)
        self.whitelisting_button.setFlat(True)
        self.whitelisting_button.setObjectName("whitelisting_button")
        self.horizontalLayout_3.addWidget(self.whitelisting_button)
        self.search_button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.search_button_2.setMaximumSize(QtCore.QSize(180, 48))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.search_button_2.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/UI_resource/audio-and-sound-speaker-cabinet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_button_2.setIcon(icon4)
        self.search_button_2.setIconSize(QtCore.QSize(48, 48))
        self.search_button_2.setCheckable(False)
        self.search_button_2.setAutoDefault(False)
        self.search_button_2.setDefault(True)
        self.search_button_2.setFlat(True)
        self.search_button_2.setObjectName("search_button_2")
        self.horizontalLayout_3.addWidget(self.search_button_2)
        self.search_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_button.setMaximumSize(QtCore.QSize(170, 48))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.search_button.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/UI_resource/controls-editor-search@32px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_button.setIcon(icon5)
        self.search_button.setIconSize(QtCore.QSize(48, 48))
        self.search_button.setCheckable(False)
        self.search_button.setAutoDefault(False)
        self.search_button.setDefault(True)
        self.search_button.setFlat(True)
        self.search_button.setObjectName("search_button")
        self.horizontalLayout_3.addWidget(self.search_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_2.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_2.setDocumentMode(True)
        self.tabWidget_2.setTabsClosable(True)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tw_table = QtWidgets.QWidget()
        self.tw_table.setObjectName("tw_table")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tw_table)
        self.gridLayout_3.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.check_all_button = QtWidgets.QPushButton(self.tw_table)
        self.check_all_button.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(7)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.check_all_button.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/UI_resource/uncheck_all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.check_all_button.setIcon(icon6)
        self.check_all_button.setIconSize(QtCore.QSize(18, 18))
        self.check_all_button.setCheckable(False)
        self.check_all_button.setAutoDefault(False)
        self.check_all_button.setDefault(True)
        self.check_all_button.setFlat(True)
        self.check_all_button.setObjectName("check_all_button")
        self.horizontalLayout_2.addWidget(self.check_all_button)
        self.delete_button = QtWidgets.QPushButton(self.tw_table)
        self.delete_button.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(7)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.delete_button.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/UI_resource/controls-editor-trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_button.setIcon(icon7)
        self.delete_button.setIconSize(QtCore.QSize(24, 24))
        self.delete_button.setCheckable(False)
        self.delete_button.setAutoDefault(False)
        self.delete_button.setDefault(True)
        self.delete_button.setFlat(True)
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout_2.addWidget(self.delete_button)
        self.add_to_bookmark_button = QtWidgets.QPushButton(self.tw_table)
        self.add_to_bookmark_button.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(7)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.add_to_bookmark_button.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/UI_resource/bookmarks-bookmark-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_to_bookmark_button.setIcon(icon8)
        self.add_to_bookmark_button.setIconSize(QtCore.QSize(24, 24))
        self.add_to_bookmark_button.setCheckable(False)
        self.add_to_bookmark_button.setAutoDefault(False)
        self.add_to_bookmark_button.setDefault(True)
        self.add_to_bookmark_button.setFlat(True)
        self.add_to_bookmark_button.setObjectName("add_to_bookmark_button")
        self.horizontalLayout_2.addWidget(self.add_to_bookmark_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 1, 2, 1)
        self.itemView = QtWidgets.QTreeWidget(self.tw_table)
        self.itemView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.itemView.setLineWidth(0)
        self.itemView.setItemsExpandable(False)
        self.itemView.setAnimated(True)
        self.itemView.setObjectName("itemView")
        self.itemView.header().setCascadingSectionResizes(False)
        self.gridLayout_3.addWidget(self.itemView, 3, 1, 1, 1)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/UI_resource/documents-folder@32px.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget_2.addTab(self.tw_table, icon9, "")
        self.verticalLayout.addWidget(self.tabWidget_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.status_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.status_label_1.setText("")
        self.status_label_1.setObjectName("status_label_1")
        self.horizontalLayout.addWidget(self.status_label_1)
        self.status_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.status_label_2.setText("")
        self.status_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.status_label_2.setObjectName("status_label_2")
        self.horizontalLayout.addWidget(self.status_label_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1235, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAdvanced = QtWidgets.QMenu(self.menubar)
        self.menuAdvanced.setObjectName("menuAdvanced")
        self.menuReport = QtWidgets.QMenu(self.menubar)
        self.menuReport.setObjectName("menuReport")
        self.menuVerify = QtWidgets.QMenu(self.menubar)
        self.menuVerify.setObjectName("menuVerify")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuInformation = QtWidgets.QMenu(self.menubar)
        self.menuInformation.setObjectName("menuInformation")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dw_treeview = QtWidgets.QDockWidget(MainWindow)
        self.dw_treeview.setObjectName("dw_treeview")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.dockWidgetContents_3)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tw_home = QtWidgets.QWidget()
        self.tw_home.setObjectName("tw_home")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tw_home)
        self.gridLayout_6.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_6.setSpacing(4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.treeWidget = QtWidgets.QTreeWidget(self.tw_home)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.gridLayout_6.addWidget(self.treeWidget, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tw_home, "")
        self.tw_bookmark = QtWidgets.QWidget()
        self.tw_bookmark.setObjectName("tw_bookmark")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tw_bookmark)
        self.gridLayout_11.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_11.setSpacing(4)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.bookmark_treeWidget = QtWidgets.QTreeWidget(self.tw_bookmark)
        self.bookmark_treeWidget.setAnimated(True)
        self.bookmark_treeWidget.setObjectName("bookmark_treeWidget")
        self.gridLayout_11.addWidget(self.bookmark_treeWidget, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tw_bookmark, "")
        self.tw_search = QtWidgets.QWidget()
        self.tw_search.setObjectName("tw_search")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tw_search)
        self.gridLayout_7.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_7.setSpacing(4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.keyfile_treeWidget = QtWidgets.QTreeWidget(self.tw_search)
        self.keyfile_treeWidget.setObjectName("keyfile_treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.keyfile_treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/box/box_green.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon10)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/box/box_apricot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon11)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/box/box_blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon12)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/box/box_orange.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon13)
        item_0 = QtWidgets.QTreeWidgetItem(self.keyfile_treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/box/box_black.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon14)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/box/box_gray.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon15)
        item_0 = QtWidgets.QTreeWidgetItem(self.keyfile_treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/box/box_red.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon16)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/box/box_pink.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon17)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/box/box_brown.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon18)
        self.gridLayout_7.addWidget(self.keyfile_treeWidget, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tw_search, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_10.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_10.setSpacing(4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.listView_2 = QtWidgets.QListView(self.tab)
        self.listView_2.setObjectName("listView_2")
        self.gridLayout_10.addWidget(self.listView_2, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget_3, 0, 0, 1, 1)
        self.dw_treeview.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dw_treeview)
        self.dw_notableview = QtWidgets.QDockWidget(MainWindow)
        self.dw_notableview.setObjectName("dw_notableview")
        self.dockWidgetContents_4 = QtWidgets.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.dockWidgetContents_4)
        self.gridLayout_8.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_8.setSpacing(4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.stackedWidget = QtWidgets.QStackedWidget(self.dockWidgetContents_4)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_8.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.dw_notableview.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dw_notableview)
        self.dw_contentsview = QtWidgets.QDockWidget(MainWindow)
        self.dw_contentsview.setObjectName("dw_contentsview")
        self.dockWidgetContents_5 = QtWidgets.QWidget()
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.dockWidgetContents_5)
        self.gridLayout_9.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_9.setSpacing(4)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.dockWidgetContents_5)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tw_text = QtWidgets.QWidget()
        self.tw_text.setObjectName("tw_text")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tw_text)
        self.gridLayout_4.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.hexview_tableWidget = QtWidgets.QTableWidget(self.tw_text)
        self.hexview_tableWidget.setMinimumSize(QtCore.QSize(480, 0))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        font.setKerning(True)
        self.hexview_tableWidget.setFont(font)
        self.hexview_tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hexview_tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.hexview_tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hexview_tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.hexview_tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.hexview_tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.hexview_tableWidget.setAutoScroll(False)
        self.hexview_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.hexview_tableWidget.setProperty("showDropIndicator", False)
        self.hexview_tableWidget.setDragDropOverwriteMode(False)
        self.hexview_tableWidget.setAlternatingRowColors(True)
        self.hexview_tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.hexview_tableWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.hexview_tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.hexview_tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.hexview_tableWidget.setShowGrid(False)
        self.hexview_tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.hexview_tableWidget.setCornerButtonEnabled(True)
        self.hexview_tableWidget.setObjectName("hexview_tableWidget")
        self.hexview_tableWidget.setColumnCount(16)
        self.hexview_tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.hexview_tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hexview_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hexview_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.hexview_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.hexview_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.hexview_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.hexview_tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.hexview_tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.hexview_tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.hexview_tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.hexview_tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.hexview_tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.hexview_tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.hexview_tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.hexview_tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.hexview_tableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.hexview_tableWidget.setHorizontalHeaderItem(15, item)
        self.hexview_tableWidget.horizontalHeader().setVisible(False)
        self.hexview_tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.hexview_tableWidget.horizontalHeader().setDefaultSectionSize(30)
        self.hexview_tableWidget.horizontalHeader().setMinimumSectionSize(30)
        self.hexview_tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.hexview_tableWidget.horizontalHeader().setStretchLastSection(False)
        self.hexview_tableWidget.verticalHeader().setVisible(False)
        self.hexview_tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.hexview_tableWidget.verticalHeader().setDefaultSectionSize(25)
        self.hexview_tableWidget.verticalHeader().setMinimumSectionSize(3)
        self.gridLayout_4.addWidget(self.hexview_tableWidget, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 0, 5, 1, 1)
        self.verticalScrollBar = QtWidgets.QScrollBar(self.tw_text)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.gridLayout_4.addWidget(self.verticalScrollBar, 0, 4, 1, 1)
        self.offset_tableWidget = QtWidgets.QTableWidget(self.tw_text)
        self.offset_tableWidget.setMinimumSize(QtCore.QSize(60, 0))
        self.offset_tableWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.offset_tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.offset_tableWidget.setObjectName("offset_tableWidget")
        self.offset_tableWidget.setColumnCount(1)
        self.offset_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.offset_tableWidget.setHorizontalHeaderItem(0, item)
        self.offset_tableWidget.horizontalHeader().setDefaultSectionSize(60)
        self.gridLayout_4.addWidget(self.offset_tableWidget, 0, 0, 1, 1)
        self.ascii_tableWidget = QtWidgets.QTableWidget(self.tw_text)
        self.ascii_tableWidget.setMaximumSize(QtCore.QSize(150, 16777215))
        self.ascii_tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ascii_tableWidget.setAutoScroll(False)
        self.ascii_tableWidget.setObjectName("ascii_tableWidget")
        self.ascii_tableWidget.setColumnCount(1)
        self.ascii_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.ascii_tableWidget.setHorizontalHeaderItem(0, item)
        self.ascii_tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.gridLayout_4.addWidget(self.ascii_tableWidget, 0, 2, 1, 1)
        self.tabWidget_4.addTab(self.tw_text, "")
        self.tw_hex = QtWidgets.QWidget()
        self.tw_hex.setObjectName("tw_hex")
        self.tabWidget_4.addTab(self.tw_hex, "")
        self.tw_transcript = QtWidgets.QWidget()
        self.tw_transcript.setObjectName("tw_transcript")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tw_transcript)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 10, 741, 192))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.tabWidget_4.addTab(self.tw_transcript, "")
        self.tw_summary = QtWidgets.QWidget()
        self.tw_summary.setObjectName("tw_summary")
        self.tabWidget_4.addTab(self.tw_summary, "")
        self.tw_notable = QtWidgets.QWidget()
        self.tw_notable.setObjectName("tw_notable")
        self.tabWidget_4.addTab(self.tw_notable, "")
        self.gridLayout_9.addWidget(self.tabWidget_4, 0, 0, 1, 1)
        self.dw_contentsview.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dw_contentsview)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setCheckable(True)
        self.actionNew.setObjectName("actionNew")
        self.actionDevice = QtWidgets.QAction(MainWindow)
        self.actionDevice.setCheckable(True)
        self.actionDevice.setObjectName("actionDevice")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setCheckable(True)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setCheckable(True)
        self.actionSave.setObjectName("actionSave")
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAdvanced.menuAction())
        self.menubar.addAction(self.menuReport.menuAction())
        self.menubar.addAction(self.menuVerify.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuInformation.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionDevice)
        self.toolBar.addAction(self.actionLoad)
        self.toolBar.addAction(self.actionSave)

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(1)
        self.stackedWidget.setCurrentIndex(1)
        self.tabWidget_4.setCurrentIndex(1)
        self.treeWidget.clicked['QModelIndex'].connect(MainWindow.ls_UI1)
        self.bookmark_treeWidget.itemClicked['QTreeWidgetItem*','int'].connect(MainWindow.ls_bookmark_UI)
        self.keyfile_treeWidget.clicked['QModelIndex'].connect(MainWindow.ls_key_UI)
        self.treeWidget.itemExpanded['QTreeWidgetItem*'].connect(MainWindow.treeWidgetExpanded_UI)
        self.whitelisting_button.clicked.connect(MainWindow.file_open)
        self.search_button.clicked.connect(MainWindow.search_button_UI)
        self.itemView.itemClicked['QTreeWidgetItem*','int'].connect(MainWindow.itemView_checked_UI)
        self.itemView.itemDoubleClicked['QTreeWidgetItem*','int'].connect(MainWindow.itemView_doubleClicked)
        self.tabWidget_2.tabCloseRequested['int'].connect(MainWindow.itemView_tab_close_button_UI)
        self.previous_button.clicked.connect(MainWindow.previous_button_UI)
        self.next_button.clicked.connect(MainWindow.next_button_UI)
        self.upper_button.clicked.connect(MainWindow.upper_button_UI)
        self.search_button_2.clicked.connect(MainWindow.LogicalImaging_button_UI)
        self.check_all_button.clicked.connect(MainWindow.check_all_button_UI)
        self.tabWidget_2.currentChanged['int'].connect(MainWindow.update_status_label)
        self.verticalScrollBar.sliderMoved['int'].connect(MainWindow.ls_hex_sliderMoved_UI)
        self.bookmark_treeWidget.itemClicked['QTreeWidgetItem*','int'].connect(MainWindow.ls_bookmark_UI)
        self.add_to_bookmark_button.clicked.connect(MainWindow.AddToBookmark_button_UI)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.whitelisting_button.setText(_translate("MainWindow", "WhiteListing"))
        self.search_button_2.setText(_translate("MainWindow", "Logical Imaging"))
        self.search_button.setText(_translate("MainWindow", "Search"))
        self.check_all_button.setText(_translate("MainWindow", "Check All"))
        self.delete_button.setText(_translate("MainWindow", "Delete"))
        self.add_to_bookmark_button.setText(_translate("MainWindow", "Add To Bookmark"))
        self.itemView.setSortingEnabled(False)
        self.itemView.headerItem().setText(0, _translate("MainWindow", "Name"))
        self.itemView.headerItem().setText(1, _translate("MainWindow", "Extension"))
        self.itemView.headerItem().setText(2, _translate("MainWindow", "Category"))
        self.itemView.headerItem().setText(3, _translate("MainWindow", "Path"))
        self.itemView.headerItem().setText(4, _translate("MainWindow", "Size"))
        self.itemView.headerItem().setText(5, _translate("MainWindow", "MODIFY_TIME"))
        self.itemView.headerItem().setText(6, _translate("MainWindow", "ACCESS_TIME"))
        self.itemView.headerItem().setText(7, _translate("MainWindow", "CREATE_TIME"))
        self.itemView.headerItem().setText(8, _translate("MainWindow", "MODIFY_ATTRIBUTE_TIME"))
        self.itemView.headerItem().setText(9, _translate("MainWindow", "BACKUP_TIME"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tw_table), _translate("MainWindow", "메인"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAdvanced.setTitle(_translate("MainWindow", "Advanced"))
        self.menuReport.setTitle(_translate("MainWindow", "Report"))
        self.menuVerify.setTitle(_translate("MainWindow", "Verify"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuInformation.setTitle(_translate("MainWindow", "Information"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.dw_treeview.setWindowTitle(_translate("MainWindow", "탐색"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tw_home), _translate("MainWindow", "Explorer"))
        self.bookmark_treeWidget.headerItem().setText(0, _translate("MainWindow", "Name"))
        self.bookmark_treeWidget.headerItem().setText(1, _translate("MainWindow", "Editor"))
        self.bookmark_treeWidget.headerItem().setText(2, _translate("MainWindow", "Time"))
        self.bookmark_treeWidget.headerItem().setText(3, _translate("MainWindow", "Explanation"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tw_bookmark), _translate("MainWindow", "Bookmark"))
        self.keyfile_treeWidget.headerItem().setText(0, _translate("MainWindow", "key_files"))
        __sortingEnabled = self.keyfile_treeWidget.isSortingEnabled()
        self.keyfile_treeWidget.setSortingEnabled(False)
        self.keyfile_treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "User_side"))
        self.keyfile_treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Document Files"))
        self.keyfile_treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "Compressed Files"))
        self.keyfile_treeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "Graphic Files"))
        self.keyfile_treeWidget.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "Multimedia Files"))
        self.keyfile_treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "System_side"))
        self.keyfile_treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "System Log Files"))
        self.keyfile_treeWidget.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "Web Browser Log Files"))
        self.keyfile_treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "ETC"))
        self.keyfile_treeWidget.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "Bad Signature Files"))
        self.keyfile_treeWidget.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "No Extension Files"))
        self.keyfile_treeWidget.topLevelItem(2).child(2).setText(0, _translate("MainWindow", "Unknown Extension Files"))
        self.keyfile_treeWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tw_search), _translate("MainWindow", "Key File"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab), _translate("MainWindow", "Time line"))
        self.dw_notableview.setWindowTitle(_translate("MainWindow", "System Warning"))
        item = self.hexview_tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "asd"))
        item = self.hexview_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.hexview_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.hexview_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.hexview_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.hexview_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "4"))
        item = self.hexview_tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "5"))
        item = self.hexview_tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "6"))
        item = self.hexview_tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "7"))
        item = self.hexview_tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "8"))
        item = self.hexview_tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "9"))
        item = self.hexview_tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "A"))
        item = self.hexview_tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "B"))
        item = self.hexview_tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "C"))
        item = self.hexview_tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "D"))
        item = self.hexview_tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "e"))
        item = self.hexview_tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "F"))
        item = self.offset_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Offset"))
        item = self.ascii_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "0123456789ABCDEF"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tw_text), _translate("MainWindow", "Hex"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tw_hex), _translate("MainWindow", "PreView"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tw_transcript), _translate("MainWindow", "Transcript"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tw_summary), _translate("MainWindow", "Summary"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tw_notable), _translate("MainWindow", "Notable"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionDevice.setText(_translate("MainWindow", "Device"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionSave.setText(_translate("MainWindow", "Save"))

import UI_resource_rc
